#!/bin/bash

is_git_repo() {
  git rev-parse --show-toplevel > /dev/null 2>&1
  result=$?
  if test $result != 0; then
    >&2 echo 'Not a git repo!'
    exit $result
  fi
}

is_git_repo

read -e -p "Enter first ref: " ref1

if [ -z "${ref1}" ]; then
  echo "Ref is required"
fi

read -e -p "Enter second ref: " ref2

if [ -z "${ref2}" ]; then
  echo "Ref is required"
fi

echo -e "\n"

git --no-pager log --pretty=format:" * %s" --no-merges --no-decorate "$ref1".."$ref2"

git --no-pager log --pretty=format:" * %s" --no-merges --no-decorate "$ref1".."$ref2"|wc -l

echo -e "\n"
