##Console

# Coloured output in terminal
msg-color=yes

# Apped module name to output
msg-module=yes

##Input

# Disable all default keybinds except listed in input.conf, also disables script keybinds when mp.add_key_binding is used
no-input-default-bindings

##GUI

save-position-on-quit

# Do not terminate after playback is complete. yes: Don't terminate if the current file is the last playlist entry.
keep-open=yes

# Disable OSC, managed by Modern X and Thumbnailer scripts
osc=no

# Start always with a GUI; override at run with `--player-operation-mode=cplayer`
player-operation-mode=pseudo-gui

# PLayback window size, prevents auto-fitting
geometry=1000x600

# Show filename on OSD when playback starts
#osd-playing-msg='${filename}'

# Maintain video aspect
keepaspect=yes

##Screenshots

# Screenshot filename to use
screenshot-template="%F - [%P]v%#01n"

# Screenshot directory
screenshot-directory="~/Pictures"

# Screebshot format
screenshot-format=png

# 0 is no compression
screenshot-png-compression=0

# Tag screenshots with the appropriate colorspace
screenshot-tag-colorspace=yes

# Same output bitdepth as video
screenshot-high-bit-depth=yes

##Audio

# Prefer Pipewire backend
ao=pipewire,pulse

# Initial volume
volume=100

# Max volume
volume-max=100

# Fix audio popping on seek
audio-stream-silence=yes

# External audio file doesn't need to exactly match filename to load
audio-file-auto=fuzzy

# Insert scaletempo when playing with higher speed
audio-pitch-correction=yes

# Try to play consecutive audio files with no silence or disruption at the point of file change
gapless-audio=weak

# Audio languages in order of preference
alang=jpn,jp,eng,en,enUS,en-US

##Subtitles

# Load all subs containing the media filename
sub-auto=fuzzy

# Subtitle language in order of preference
slang=eng,en,enUS,en-US

# Subtitle font size
sub-font-size=36

# Use embedded fonts for SSA/ASS subtitles
embeddedfonts=yes

# Correctly show embedded subs when seeking
demuxer-mkv-subtitle-preroll

##GPU,Video

# Loads high quality OpenGL options when using vo=gpu as video output
profile=gpu-hq

# Specify the video output backend
vo=gpu

# Hardware acceleration
hwdec=vaapi

# Codec to hardware accelerate; check `vainfo`
hwdec-codecs=h264,mpeg2video,vc1,hevc

# Selects the GPU context; comment for X11
gpu-context=wayland

# Don't drop frames while seeking
hr-seek-framedrop=no

# Always allow seeking
force-seekable=yes

# Deband filter
deband=yes

# Higher=better quality but more GPU usage
deband-iterations=2

# Deband strength
deband-threshold=60

# Range of deband, too high destroys video
deband-range=16

# Inject grain to cover up bad banding, higher value needed for poor sources
deband-grain=60

# Automatic dither depth selection. If output bit depth cannot be detected, 8 bits per component
dither-depth=auto

# Suited for iGPU
# Defaults for GPU-HQ
scale=spline36
dscale=mitchell
cscale=spline36

##Yotube-DL/YT-DLP Options

# Quality Video:720p, Codec: h264 (hw acceleration)
ytdl-format="bestvideo[height<=720][vcodec=h264]+bestaudio/best[height<=720]"

##Cache

# Cache media
cache=yes

# Demuxer buffer size ~105 MB
demuxer-max-bytes=104857600

# Demuxer cache seconds
demuxer-readahead-secs=600

# Seekable cache
demuxer-seekable-cache=yes
